image:
  repository: tccr.io/truecharts/strapi
  tag: v3.6.8@sha256:a36075a1a9cc9802e77772f765b189ff1f4216c11de80fb1c36b1a44551cdcc6
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  DATABASE_CLIENT: "postgres"
  DATABASE_PORT: 5432
  DATABASE_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  DATABASE_USERNAME: "{{ .Values.postgresql.postgresqlUsername }}"
  NODE_ENV: "production"
  EXTRA_ARGS: ""
  DATABASE_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost
  DATABASE_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password

service:
  main:
    ports:
      main:
        port: 1337
        targetPort: 1337

persistence:
  data:
    enabled: true
    mountPath: "/srv/app"

# Enabled postgres
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: strapi
  postgresqlDatabase: strapi

portal:
  enabled: true
