annotations:
  truecharts.org/SCALE-support: "true"
  truecharts.org/catagories: |
    - database
  truecharts.org/grade: U
apiVersion: v2
appVersion: 14.5.0
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 10.5.6
description: PostgresSQL
home: https://truecharts.org/docs/charts/dependency/postgresql
icon: https://truecharts.org/img/hotlink-ok/chart-icons/postgresql.png
keywords:
- postgres
- postgressql
- dtabase
- sql
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: postgresql
sources:
- https://github.com/truecharts/charts/tree/master/charts/dependency/postgresql
- https://www.postgresql.org/
type: application
version: 8.0.69
