image:
  repository: tccr.io/truecharts/postgresql
  pullPolicy: IfNotPresent
  tag: 14.5.0@sha256:cb08d8828c852a23a2665bceac109b9d4ef8c388d4e859ec32aca0a3a8431bae

controller:
  # -- Set the controller type.
  # Valid options are deployment, daemonset or statefulset
  type: statefulset
  # -- Number of desired pods
  replicas: 1
  # -- Set the controller upgrade strategy
  # For Deployments, valid values are Recreate (default) and RollingUpdate.
  # For StatefulSets, valid values are OnDelete and RollingUpdate (default).
  # DaemonSets ignore this.
  strategy: RollingUpdate
  rollingUpdate:
    # -- Set deployment RollingUpdate max unavailable
    unavailable: 1
    # -- Set deployment RollingUpdate max surge
    surge:
    # -- Set statefulset RollingUpdate partition
    partition:
  # -- ReplicaSet revision history limit
  revisionHistoryLimit: 3

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 5432
        targetPort: 5432

## TODO: Fix the backup-on-upgrade system
enableUpgradeBackup: false

podSecurityContext:
  runAsGroup: 0

volumeClaimTemplates:
  db:
    enabled: true
    mountPath: "/bitnami/postgresql"

# -- Probe configuration
# -- [[ref]](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
# @default -- See below
probes:
  # -- Liveness probe configuration
  # @default -- See below
  liveness:
    # -- Enable the liveness probe
    enabled: true
    # -- Set this to `true` if you wish to specify your own livenessProbe
    custom: true
    # -- The spec field contains the values for the default livenessProbe.
    # If you selected `custom: true`, this field holds the definition of the livenessProbe.
    # @default -- See below
    spec:
      exec:
        command:
          - sh
          - -c
          - "until pg_isready -U ${POSTGRES_USER} -h localhost; do sleep 2 ; done"

  # -- Redainess probe configuration
  # @default -- See below
  readiness:
    # -- Enable the readiness probe
    enabled: true
    # -- Set this to `true` if you wish to specify your own readinessProbe
    custom: true
    # -- The spec field contains the values for the default readinessProbe.
    # If you selected `custom: true`, this field holds the definition of the readinessProbe.
    # @default -- See below
    spec:
      exec:
        command:
          - sh
          - -c
          - "until pg_isready -U ${POSTGRES_USER} -h localhost; do sleep 2 ; done"
  # -- Startup probe configuration
  # @default -- See below
  startup:
    # -- Enable the startup probe
    enabled: true
    custom: true
    # -- The spec field contains the values for the default livenessProbe.
    # If you selected `custom: true`, this field holds the definition of the livenessProbe.
    # @default -- See below
    spec:
      exec:
        command:
          - sh
          - -c
          - "until pg_isready -U ${POSTGRES_USER} -h localhost; do sleep 2 ; done"

postgresqlPassword: "testpass"
postgresqlUsername: "test"
postgresqlDatabase: "test"
postgrespassword: "testroot"
existingSecret: ""

secret:
  credentials:
    enabled: true
    data:
      postgresql-password: '{{ ( .Values.postgresqlPassword | default "empty" ) }}'
      postgresql-postgres-password: '{{ ( .Values.postgrespassword | default "empty" ) }}'

env:
  POSTGRES_PASSWORD:
    secretKeyRef:
      name: '{{ .Values.existingSecret | default ( printf "%s-credentials" ( include "tc.common.names.fullname" . ) ) }}'
      key: "postgresql-password"
  POSTGRESQL_POSTGRES_PASSWORD:
    secretKeyRef:
      name: '{{ .Values.existingSecret | default ( printf "%s-credentials" ( include "tc.common.names.fullname" . ) ) }}'
      key: "postgresql-postgres-password"
  POSTGRES_USER: "{{ .Values.postgresqlUsername }}"
  POSTGRES_DB: "{{ .Values.postgresqlDatabase }}"
# POSTGRESQL_POSTGRES_PASSWORD: "{{ .Values.postgrespassword }}"
# POSTGRESQL_PASSWORD: "{{ .Values.password }}"

portal:
  enabled: false
